import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const mainFontR = localFont({
  src: '../fonts/HakgyoansimDunggeunmisoTTF-R.woff2',
  variable: '--font-mainFontR',
  weight: '400',
});

const mainFontB = localFont({
  src: '../fonts/HakgyoansimDunggeunmisoTTF-B.woff2',
  variable: '--font-mainFontB',
  weight: '700',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${mainFontB.variable} ${mainFontR.variable}`}>
        {children}
      </body>
    </html>
  );
}
